# In your static/admin/config.yml file

backend: 
   name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        folder: "content/blog"
        create: true
        widget: "list"
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          - {label: Content, name: excerpt, widget: text}
          - {label: Image, name: image, widget: image}
          - {label: Date, name: date,  widget: datetime }
