# In your static/admin/config.yml file

backend: 
   name: github
   repo: MajaL1/gatsbyNews

media_folder: static/assets
public_folder: assets

collections:
      - name: "home"
        label: "Novica"
        description: "test"
        folder: "content/blog"
        create: true
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
        editor:
         preview: false
        filter:
         - field: publication_url
         - value: ""
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          - {label: Content, name: excerpt, widget: text}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Date, name: date,  widget: datetime }
        widget: list
