# In your static/admin/config.yml file
backend: 
   name: github
   repo: MajaL1/gatsbyNews

media_folder: static/assets
public_folder: assets

collections:
  - name: home
    label: Blog
    description: "test1"
    folder: "content/blog"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }