# In your static/admin/config.yml file

backend: 
   name: test-repo

media_folder: static/assets
public_folder: assets

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post124" # Used in the UI, ie.: "New Post"
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: {{slug}}
    fields: # The fields each document in this collection have
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Datum objave", name: "date", widget: "datetime"}
      - {label: "Opis", name: "intro", widget: "text"}
      - {label: "Slika", name: "image", widget: "image", required: false}
      - {label: "Vsebina", name: "body", widget: "markdown"}
